In [39]:
import pandas as pd
import numpy as np
from sklearn.svm import SVC
from sklearn.metrics.pairwise import pairwise_kernels, polynomial_kernel

# Kernel Matrix for AB (+Negatif -Netral)

In [40]:
train_AB = pd.read_excel(r'C:\Users\ASUS\skripsi\train_AB.xlsx')

In [41]:
train_AB = train_AB.drop(['Unnamed: 0'], axis = 1)
train_AB

a  aaaaaaaaaaaaanjing  aaargh  aarrgh  ab  abang  abdillah  absen  \
0    0.0                 0.0       0       0   0    0.0       0.0    0.0   
1    0.0                 0.0       0       0   0    0.0       0.0    0.0   
2    0.0                 0.0       0       0   0    0.0       0.0    0.0   
3    0.0                 0.0       0       0   0    0.0       0.0    0.0   
4    0.0                 0.0       0       0   0    0.0       0.0    0.0   
..   ...                 ...     ...     ...  ..    ...       ...    ...   
954  0.0                 0.0       0       0   0    0.0       0.0    0.0   
955  0.0                 0.0       0       0   0    0.0       0.0    0.0   
956  0.0                 0.0       0       0   0    0.0       0.0    0.0   
957  0.0                 0.0       0       0   0    0.0       0.0    0.0   
958  0.0                 0.0       0       0   0    0.0       0.0    0.0   

          abt  abu  ...   yt  yudisium  yuk  yukz  yupi  zaky  zen  zenius  \
0    0.417246  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
1    0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
2    0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
3    0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
4    0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
..        ...  ...  ...  ...       ...  ...   ...   ...   ...  ...     ...   
954  0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
955  0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
956  0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
957  0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   
958  0.000000  0.0  ...  0.0       0.0  0.0     0   0.0     0  0.0     0.0   

     zoom  zoomnya  
0     0.0        0  
1     0.0        0  
2     0.0        0  
3     0.0        0  
4     0.0        0  
..    ...      ...  
954   0.0        0  
955   0.0        0  
956   0.0        0  
957   0.0        0  
958   0.0        0  

[959 rows x 2647 columns]

In [42]:
AB = train_AB.to_numpy()
AB

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [43]:
kernel_AB = polynomial_kernel(AB, degree = 3, gamma = 1.0029993182196073, coef0 = 1.8)
kernel_AB

array([[22.02261956,  5.92828903,  5.89564177, ...,  5.832     ,
         5.86556717,  5.88119968],
       [ 5.92828903, 22.02261956,  6.01105178, ...,  5.832     ,
         5.92615058,  5.97021712],
       [ 5.89564177,  6.01105178, 22.02261956, ...,  6.96771025,
         5.89423091,  5.92328125],
       ...,
       [ 5.832     ,  5.832     ,  6.96771025, ..., 22.02261956,
         5.832     ,  5.832     ],
       [ 5.86556717,  5.92615058,  5.89423091, ...,  5.832     ,
        22.02261956,  8.32621133],
       [ 5.88119968,  5.97021712,  5.92328125, ...,  5.832     ,
         8.32621133, 22.02261956]])

In [57]:
df_AB = pd.DataFrame(kernel_AB)
df_AB.to_excel(r"C:\Users\ASUS\skripsi\kernel_AB.xlsx")

In [44]:
ab_1 = AB[0]
ab_2 = AB[1]
ab_3 = AB[2]
ab_959 = AB[958]

ab_11 = ab_1.dot(ab_1)
ab_12 = ab_1.dot(ab_2)
ab_13 = ab_1.dot(ab_3)
ab_959959 = ab_959.dot(ab_959)

print("Dot product x_1*x_1 adalah:", ab_11)
print("Dot product x_1*x_2 adalah:", ab_12)
print("Dot product x_1*x_3 adalah:", ab_13)
print("Dot product x_959*x_959 adalah:", ab_959959)

Dot product x_1*x_1 adalah: 1.0
Dot product x_1*x_2 adalah: 0.009822792490294871
Dot product x_1*x_3 adalah: 0.006504325108123742
Dot product x_959*x_959 adalah: 1.0


# Kernel Matrix for AC (+Negatif -Positif)

In [45]:
train_AC = pd.read_excel(r'C:\Users\ASUS\skripsi\train_AC.xlsx')

In [46]:
train_AC = train_AC.drop(['Unnamed: 0'], axis = 1)
train_AC

a  aaaaaaaaaaaaanjing  aaargh  aarrgh   ab  abang  abdillah  absen  \
0    0.0                 0.0     0.0     0.0  0.0      0         0      0   
1    0.0                 0.0     0.0     0.0  0.0      0         0      0   
2    0.0                 0.0     0.0     0.0  0.0      0         0      0   
3    0.0                 0.0     0.0     0.0  0.0      0         0      0   
4    0.0                 0.0     0.0     0.0  0.0      0         0      0   
..   ...                 ...     ...     ...  ...    ...       ...    ...   
361  0.0                 0.0     0.0     0.0  0.0      0         0      0   
362  0.0                 0.0     0.0     0.0  0.0      0         0      0   
363  0.0                 0.0     0.0     0.0  0.0      0         0      0   
364  0.0                 0.0     0.0     0.0  0.0      0         0      0   
365  0.0                 0.0     0.0     0.0  0.0      0         0      0   

     abt  abu  ...   yt  yudisium  yuk  yukz  yupi  zaky  zen  zenius  zoom  \
0      0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
1      0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
2      0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
3      0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
4      0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
..   ...  ...  ...  ...       ...  ...   ...   ...   ...  ...     ...   ...   
361    0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
362    0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
363    0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
364    0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   
365    0  0.0  ...  0.0       0.0  0.0   0.0     0   0.0    0     0.0   0.0   

     zoomnya  
0        0.0  
1        0.0  
2        0.0  
3        0.0  
4        0.0  
..       ...  
361      0.0  
362      0.0  
363      0.0  
364      0.0  
365      0.0  

[366 rows x 2647 columns]

In [47]:
AC = train_AC.to_numpy()
AC

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [48]:
kernel_AC = polynomial_kernel(AC, degree = 3, gamma = 1.0029993182196073, coef0 = 1.8)
kernel_AC

array([[22.02261956,  6.19209394,  5.88490499, ...,  5.86448809,
         6.49782817,  5.8735707 ],
       [ 6.19209394, 22.02261956,  5.87533496, ...,  5.85861686,
         6.16187179,  5.8660549 ],
       [ 5.88490499,  5.87533496, 22.02261956, ...,  5.9146133 ,
         5.88053282,  5.93779305],
       ...,
       [ 5.86448809,  5.85861686,  5.9146133 , ..., 22.02261956,
         5.86180606,  5.89689104],
       [ 6.49782817,  6.16187179,  5.88053282, ...,  5.86180606,
        22.02261956,  5.87013724],
       [ 5.8735707 ,  5.8660549 ,  5.93779305, ...,  5.89689104,
         5.87013724, 22.02261956]])

In [49]:
ac_1 = AC[0]
ac_2 = AC[1]
ac_3 = AC[2]
ac_366 = AC[365]

ac_11 = ac_1.dot(ac_1)
ac_12 = ac_1.dot(ac_2)
ac_13 = ac_1.dot(ac_3)
ac_366366 = ac_366.dot(ac_366)

print("Dot product x_1*x_1 adalah:", ac_11)
print("Dot product x_1*x_2 adalah:", ac_12)
print("Dot product x_1*x_3 adalah:", ac_13)
print("Dot product x_366*x_366 adalah:", ac_366366)

Dot product x_1*x_1 adalah: 1.0000000000000002
Dot product x_1*x_2 adalah: 0.03620077193327184
Dot product x_1*x_3 adalah: 0.005410296587479568
Dot product x_366*x_366 adalah: 1.0


In [58]:
df_AC = pd.DataFrame(kernel_AC)
df_AC.to_excel(r"C:\Users\ASUS\skripsi\kernel_AC.xlsx")

# Kernel Matrix for BC (+Netral -Positif)

In [50]:
train_BC = pd.read_excel(r'C:\Users\ASUS\skripsi\train_BC.xlsx')

In [51]:
train_BC = train_BC.drop(['Unnamed: 0'], axis = 1)
train_BC

a  aaaaaaaaaaaaanjing  aaargh  aarrgh   ab  abang  abdillah  absen  \
0    0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
1    0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
2    0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
3    0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
4    0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
..   ...                 ...     ...     ...  ...    ...       ...    ...   
926  0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
927  0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
928  0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
929  0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   
930  0.0                   0     0.0     0.0  0.0    0.0       0.0    0.0   

          abt  abu  ...  yt  yudisium  yuk  yukz  yupi  zaky  zen  zenius  \
0    0.417246  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
1    0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
2    0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
3    0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
4    0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
..        ...  ...  ...  ..       ...  ...   ...   ...   ...  ...     ...   
926  0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
927  0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
928  0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
929  0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   
930  0.000000  0.0  ...   0       0.0  0.0   0.0   0.0   0.0  0.0     0.0   

     zoom  zoomnya  
0     0.0      0.0  
1     0.0      0.0  
2     0.0      0.0  
3     0.0      0.0  
4     0.0      0.0  
..    ...      ...  
926   0.0      0.0  
927   0.0      0.0  
928   0.0      0.0  
929   0.0      0.0  
930   0.0      0.0  

[931 rows x 2647 columns]

In [52]:
BC = train_BC.to_numpy()
BC

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [53]:
kernel_BC = polynomial_kernel(BC, degree = 3, gamma = 1.0029993182196073, coef0 = 1.8)
kernel_BC

array([[22.02261956,  5.92828903,  5.89564177, ...,  5.832     ,
         5.86556717,  5.88119968],
       [ 5.92828903, 22.02261956,  6.01105178, ...,  5.832     ,
         5.92615058,  5.97021712],
       [ 5.89564177,  6.01105178, 22.02261956, ...,  6.96771025,
         5.89423091,  5.92328125],
       ...,
       [ 5.832     ,  5.832     ,  6.96771025, ..., 22.02261956,
         5.832     ,  5.832     ],
       [ 5.86556717,  5.92615058,  5.89423091, ...,  5.832     ,
        22.02261956,  8.32621133],
       [ 5.88119968,  5.97021712,  5.92328125, ...,  5.832     ,
         8.32621133, 22.02261956]])

In [54]:
bc_1 = BC[0]
bc_2 = BC[1]
bc_3 = BC[2]
bc_931 = BC[930]

bc_11 = bc_1.dot(bc_1)
bc_12 = bc_1.dot(bc_2)
bc_13 = bc_1.dot(bc_3)
bc_931931 = bc_931.dot(bc_931)

print("Dot product x_1*x_1 adalah:", bc_11)
print("Dot product x_1*x_2 adalah:", bc_12)
print("Dot product x_1*x_3 adalah:", bc_13)
print("Dot product x_931*x_931 adalah:", bc_931931)

Dot product x_1*x_1 adalah: 1.0
Dot product x_1*x_2 adalah: 0.009822792490294871
Dot product x_1*x_3 adalah: 0.006504325108123742
Dot product x_931*x_931 adalah: 1.0


In [59]:
df_BC = pd.DataFrame(kernel_BC)
df_BC.to_excel(r"C:\Users\ASUS\skripsi\kernel_BC.xlsx")

# Kernel Matrix for Decision Function 